### ISSUE TITLE
Width not set so the overflow will be Uncontrollable 

### ISSUE THREAD

**Issue by firstmetcs** [foisonocean/react-dynamic-font#8] opened 2021-05-07 09:12 UTC
![image](https://user-images.githubusercontent.com/32634443/117426923-0c66a080-af57-11eb-97c9-29002a044c38.png)

When the span element set the width to 100%， it can be normal

![image](https://user-images.githubusercontent.com/32634443/117427159-5485c300-af57-11eb-902f-bd8ac6ae68c7.png)

**Comment by hronro** [comment] 2021-05-07 09:22
Can you provide a reproducible repository or something like codesandbox?

**Comment by hronro** [comment] 2021-05-10 06:05
I'll close this issue since it need more information.

Feel free to reopen it if you can provide a reproducible repo.

**Closed as completed by hronro** 2021-05-10 06:05 UTC
